function encabezadopagina(){
	//Utilizar esta herramienta para convertir bloque HTML en una sola linea
	//http://www.textfixer.com/html/compress-html-compression.php
	//http://www.textfixer.com/html/uncompress-html-code.php
	var valorhtml = '<header id="main-header"> <div class="header-top"> <div class="container"> <div class="col-md-6"> <ul class="header-top-ul"> <li class=""> <a href="#contact"> <span class="glyphicon glyphicon-earphone"></span> 333-4444 </a> </li> <li class=""> <a href="#contact"> <span class="glyphicon glyphicon-envelope"></span> ovata@ventas.com.pe </a> </li> </ul> </div> <div class="col-md-6"> <div class="header-top-right"> <ul class="header-top-ul"> <li class=""><a href="#portfolio">Clientes</a></li> <!-- <li class=""><a href="#tecnologia">Tecnología</a></li> --> <li class=""><a href="#blog">Blog</a></li> </ul> </div> </div> <!-- <div class="col-md-2"> <div class="header-top-right"> <div class="social-media"> <ul class="items-social"> <li><a title="Facebook" class="image-facebook" href="#">Facebook</a></li> <li><a title="Twitter" class="image-twitter" href="#">Twitter</a></li> <li><a title="Linkedin" class="image-linkedin" href="#">Linkedin</a></li> <li><a title="Google +" class="image-googlem" href="#">Google+</a></li> </ul> </div> </div> </div> --> </div> </div> <nav class="navbar navbar-default navbar-fixed-top"> <div class="container"> <div class="navbar-header"> <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"> <span class="icon-bar"> </span> <span class="icon-bar"> </span> <span class="icon-bar"> </span> </button> <!-- <a class="navbar-brand" href="#"> OVATA <span class="logo-dec">Systems</span> </a> --> <a class="navbar-brand" href="#"> <img alt="OVATA" src="../img/logo2.png" class="img-responsive"> </a> </div> <div class="collapse navbar-collapse" id="myNavbar"> <ul class="nav navbar-nav navbar-right"> <li class="active"><a href="../index.html">INICIO</a></li> <li class="dropdown"> <!-- <a href="#feature">SOLUCIONES</a> --> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> SOLUCIONES <span class="caret"> </span> </a> <ul class="dropdown-menu"> <li><a href="erp.html">ERP (ENTERPRISE RESOURCE PLANNING)</a></li> <li><a href="#">SISTEMA DE RECURSOS HUMANOS</a></li><li role="separator" class="divider"></li> <li><a href="#">SISTEMA DE PUNTO DE VENTA</a></li> <li><a href="#">MONITOREO DE TIEMPOS Y CONSUMOS</a></li> </ul> </li> <li class="dropdown"> <!-- <a href="#service">SERVICIOS</a> --> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> SERVICIOS <span class="caret"> </span> </a> <ul class="dropdown-menu"> <li><a href="#service">DESARROLLO DE SOFTWARE</a></li> <li><a href="#service">DESARROLLO MÓVIL</a></li> </ul> </li> <li class=""><a href="#testimonial">NOSOTROS</a></li> <li class=""><a href="#contact">CONTÁCTENOS</a></li> </ul> </div> </div> </nav></header>'

	document.write(valorhtml);
}

function piepagina(){
	var valorhtml = '<footer id="footer"> <div class="container white"> <div class="row"> <div class="col-md-4"> <h4>CONTÁCTENOS</h4> <div class="loction-info"> <p> <i class="fa fa-map-marker fa-fw pull-left fa-2x glyphicon glyphicon-globe"></i>LIMA Ate, TX 555072 - Perú</p> <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x glyphicon glyphicon-envelope"></i>info@baker.com</p> <p><i class="fa fa-phone fa-fw pull-left fa-2x glyphicon glyphicon glyphicon-earphone"></i>+41 5787 2323</p> </div> </div> <div class="col-md-4"> <h4>SOLUCIONES</h4> <p><a href="#">Software Integrado ERP</a></p> <p><a href="#">Compras y Cuentas por Pagar</a></p> <p><a href="#">Ventas y Cuentas por Cobrar</a></p> </div> <div class="col-md-4"> <h4>SERVICIOS</h4> <p><a href="#">Desarrollo de Software a Medida</a></p> <p><a href="#">Aplicaciones Móviles Android y AOS</a></p> </div> </div> <div class="row"> <hr> <div class="col-md-6"> <div class="content-manager"> <nav> <ul> <li><a target="_blank" class="image-facebook" href="#"> Facebook </a></li> <li><a target="_blank" class="image-twitter" href="#"> Twitter </a></li> <li><a target="_blank" class="image-linkedin" href="#"> Linkedin </a></li> <li><a target="_blank" class="image-googlem" href="#"> Google + </a></li> </ul> </nav> </div> </div> <div class="col-md-6"> <img src="img/microsoft64.png" class="img-rounded"> <img src="img/visualstudio64.png" class="img-rounded"> <img src="img/php64.png" class="img-rounded"> <img src="img/android642.png" class="img-rounded"> <img src="img/iOS64.png" class="img-rounded"> </div> </div> <div class="row"> <hr> <div class="col-md-12 text-center"> <p>© 2017 Todos los derechos reservados.</p> </div> </div> </div></footer>';
	document.write(valorhtml);
}

function seccioncontacto(){
	var valorhtml = '<section id="contact" class="wow fadeInUp delay-05s"> <div class="bg-contcolor"> <div class="container section-padding"> <div class="row contact-form"> <div class="col-md-12 text-center white"> <h2 class="service-title pad-bt15">Contáctenos</h2> <p class="sub-title pad-bt15">Si necesita ayuda o tiene dudas sobre nuestros servicios o soluciones, escríbanos llenando el siguiente formulario. <br> A la brevedad le atenderá nuestro equipo de servicios.</p> </div> <div class="col-lg-4 col-sm-4"> <div class="form-group"> <input type="text" name="name" class="form-control backg-name" id="name" placeholder="Su nombre" data-rule="minlen:4" data-msg="Please enter at least 4 chars" /> <div class="validation"></div> </div> </div> <div class="col-lg-4 col-sm-4"> <div class="form-group"> <input type="email" class="form-control backg-email" name="email" id="email" placeholder="Su e-mail" data-rule="email" data-msg="Please enter a valid email" /> <div class="validation"></div> </div> </div> <div class="col-lg-4 col-sm-4"> <div class="form-group"> <input type="text" class="form-control backg-message" name="subject" id="subject" placeholder="Asunto" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" /> <div class="validation"></div> </div> </div> <div class="col-lg-12 col-sm-12"> <div class="form-group"> <textarea class="form-control backg-message" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Su mensaje"></textarea> <div class="validation"></div> </div> <button type="submit" class="btn btn-primary btn-submit pull-right">ENVIAR</button> </div> </div> </div> </div> </section>';
	document.write(valorhtml);
}

function seccionnosotros(){
	var valorhtml = '<section id="testimonial" class="wow fadeInUp delay-05s"> <div class="bg-testicolor"> <div class="container section-padding"> <div class="row"> <div class="col-md-12 text-center"> <h2 class="service-title pad-bt15">Ovata Systems</h2> <p class="sub-title pad-bt15">Ovata es una ...<br>tempor incididunt ut labore et dolore magna aliqua.</p> <hr class="bottom-line"> </div> <div class="col-lg-4 col-sm-4 text-center"> <h2>Misión</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost.</p> </div> <div class="col-lg-4 col-sm-4 text-center"> <h2>Visión</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost.</p> </div> <div class="col-lg-4 col-sm-4 text-center"> <h2>Equipo</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost.</p> </div> </div> </div> </div></section>';
	document.write(valorhtml);
}

function seccionblog(){
	var valorhtml = '<section id="blog" class="section-padding wow fadeInUp delay-05s"> <div class="container"> <div class="row"> <div class="col-md-12 text-center"> <h2 class="service-title pad-bt15">Síguenos en nuestro blog</h2> <p class="sub-title pad-bt15">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod<br>tempor incididunt ut labore et dolore magna aliqua.</p> <hr class="bottom-line"> </div> <div class="col-md-4 col-sm-6 col-xs-12"> <div class="blog-sec"> <div class="blog-img"> <a href=""> <img src="img/tablet2.png" class="img-responsive"> </a> </div> <div class="blog-info"> <h2>This is Lorem ipsum heading.</h2> <div class="blog-comment"> <p>Posted In: <span>Legal Advice</span></p> <p> <span><a href="#"><i class="fa fa-comments"></i></a> 15</span> <span><a href="#"><i class="fa fa-eye"></i></a> 11</span></p> </div> <p>We cannot expect people to have respect for laws and orders until we teach respect to those we have entrusted to enforce those laws all the time. we always want to help people cordially.</p> </div> </div> </div> <div class="col-md-4 col-sm-6 col-xs-12"> <div class="blog-sec"> <div class="blog-img"> <a href=""> <img src="img/tsloginbillar.png" class="img-responsive"> </a> </div> <div class="blog-info"> <h2>This is Lorem ipsum heading.</h2> <div class="blog-comment"> <p>Posted In: <span>Legal Advice</span></p> <p> <span><a href="#"><i class="fa fa-comments"></i></a> 15</span> <span><a href="#"><i class="fa fa-eye"></i></a> 11</span></p> </div> <p>We cannot expect people to have respect for laws and orders until we teach respect to those we have entrusted to enforce those laws all the time. we always want to help people cordially.</p> </div> </div> </div> <div class="col-md-4 col-sm-6 col-xs-12"> <div class="blog-sec"> <div class="blog-img"> <a href=""> <img src="img/2.png" class="img-responsive"> </a> </div> <div class="blog-info"> <h2>This is Lorem ipsum heading.</h2> <div class="blog-comment"> <p>Posted In: <span>Legal Advice</span></p> <p> <span><a href="#"><i class="fa fa-comments"></i></a> 15</span> <span><a href="#"><i class="fa fa-eye"></i></a> 11</span></p> </div> <p>We cannot expect people to have respect for laws and orders until we teach respect to those we have entrusted to enforce those laws all the time. we always want to help people cordially.</p> <div class="brn-btn text-center"><a href="#" class="btn btn-more">Visitar el blog</a> </div> </div> </div> </div> </div> </div> </section>';
	document.write(valorhtml);
}

function seccionclientes(){
	var valorhtml = '<section id="portfolio" class="section-padding wow fadeInUp delay-05s"> <div class="container"> <div class="row"> <div class="col-md-12 text-center"> <h2 class="service-title pad-bt15">Portafolio de Soluciones</h2> <p class="sub-title pad-bt15">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod<br>tempor incididunt ut labore et dolore magna aliqua.</p> <hr class="bottom-line"> </div> <div class="col-md-4 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15"> <figure> <img src="img/tsloginbillar.png" class="img-responsive"> <figcaption> <h2>Software Integrado ERP</h2> <p>Software integrado ERP desarrollado en Visual Studio .NET y SQL SERVER.<br> Adaptable para cualquier giro de negocio, desde comercial y servicios. Soporte en Hardware, Windows XP y hasta la versión reciente.</p> </figcaption> </figure> </div> <div class="col-md-4 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15"> <figure> <img src="img/2.png" class="img-responsive"> <figcaption> <h2>Project For Everyone</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost.</p> </figcaption> </figure> </div> <div class="col-md-4 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15"> <figure> <img src="img/1.png" class="img-responsive"> <figcaption> <h2>Project For Everyone</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost.</p> </figcaption> </figure> </div> </div> </div></section>';
	document.write(valorhtml);
}