function encabezadopagina(){
	//Utilizar esta herramienta para convertir bloque HTML en una sola linea
	//http://www.textfixer.com/html/compress-html-compression.php
	//http://www.textfixer.com/html/uncompress-html-code.php
	var valorhtml = '<header id="main-header"> <div class="header-top"> <div class="container"> <div class="col-md-10"> <div class="header-top-right"> <ul class="header-top-ul"> <li class=""><a href="#portfolio">Clientes</a></li> <li class=""><a href="#tecnologia">Tecnología</a></li> <li class=""><a href="#blog">Blog</a></li> </ul> </div> </div> <div class="col-md-2"> <div class="header-top-right"> <div class="social-media"> <ul class="items-social"> <li><a title="Facebook" class="image-facebook" href="#">Facebook</a></li> <li><a title="Twitter" class="image-twitter" href="#">Twitter</a></li> <li><a title="Linkedin" class="image-linkedin" href="#">Linkedin</a></li> <li><a title="Google +" class="image-googlem" href="#">Google+</a></li> </ul> </div> </div> </div> </div> </div> <nav class="navbar navbar-default navbar-fixed-top"> <div class="container"> <div class="navbar-header"> <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a class="navbar-brand" href="#">DE<span class="logo-dec">SOFT</span></a> </div> <div class="collapse navbar-collapse" id="myNavbar"> <ul class="nav navbar-nav navbar-right"> <li class="active"><a href="#main-header">INICIO</a></li> <li class="dropdown"> <!-- <a href="#feature">SOLUCIONES</a> --> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SOLUCIONES <span class="caret"></span></a> <ul class="dropdown-menu"> <li><a href="#">DESOFT INTEGRADO ERP</a></li> <li><a href="#">COMPRAS Y CUENTAS POR PAGAR</a></li> <li><a href="#">VENTAS Y CUENTAS POR COBRAR</a></li> <li><a href="#">LOGÍSTICA Y ALMACENES</a></li> <li role="separator" class="divider"></li> <li><a href="#">TESORERÍA</a></li> <li role="separator" class="divider"></li> <li><a href="#">SOFTWARE PARA BILLARES</a></li> </ul> </li> <li class="dropdown"> <!-- <a href="#service">SERVICIOS</a> --> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SERVICIOS <span class="caret"></span></a> <ul class="dropdown-menu"> <li><a href="#service">DESARROLLO DE SOFTWARE</a></li> <li><a href="#service">DESARROLLO MÓVIL</a></li> </ul> </li> <li class=""><a href="#testimonial">NOSOTROS</a></li> <li class=""><a href="#contact">CONTÁCTENOS</a></li> </ul> </div> </div> </nav> </header>'

	document.write(valorhtml);
}

function piepagina(){
	var valorhtml = '<footer id="footer"> <div class="container"> <div class="row"> <div class="col-md-4 white"> <h4>CONTÁCTENOS</h4> <div class="loction-info"> <p> <i class="fa fa-map-marker fa-fw pull-left fa-2x glyphicon glyphicon-globe"></i>LIMA Ate, TX 555072 - Perú</p> <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x glyphicon glyphicon-envelope"></i>info@baker.com</p> <p><i class="fa fa-phone fa-fw pull-left fa-2x glyphicon glyphicon glyphicon-earphone"></i>+41 5787 2323</p> </div> </div> <div class="col-md-4 text-center"> <h4>SOLUCIONES</h4> <p><a href="#">Software Integrado ERP</a></p> <p><a href="#">Compras y Cuentas por Pagar</a></p> <p><a href="#">Ventas y Cuentas por Cobrar</a></p> <h4>SERVICIOS</h4> <p><a href="#">Desarrollo de Software a Medida</a></p> <p><a href="#">Aplicaciones Móviles Android y AOS</a></p> </div> <div class="col-md-4 text-center"> <h4>Síguenos en:</h4> <div class="content-manager manager-hidden"> <nav> <ul> <li><a target="_blank" class="image-facebook" href="#"> Facebook </a></li> <li><a target="_blank" class="image-twitter" href="#"> Twitter </a></li> <li><a target="_blank" class="image-linkedin" href="#"> Linkedin </a></li> <li><a target="_blank" class="image-googlem" href="#"> Google + </a></li> </ul></nav> </div> <h4>Tecnologías</h4> <img src="img/microsoft64.png" class="img-rounded"> <img src="img/visualstudio64.png" class="img-rounded"> <img src="img/php64.png" class="img-rounded"> <img src="img/android642.png" class="img-rounded"> <img src="img/iOS64.png" class="img-rounded"> </div> </div> <div class="row"> <div class="col-md-12 text-center"> <hr> <p>DeSoft Solutions © 2017 Todos los derechos reservados.</p> </div> </div> </div> </footer>';
	document.write(valorhtml);
}